"""updated models

Revision ID: 30cb763ba25b
Revises: 760200d81252
Create Date: 2023-08-30 10:17:32.574050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cb763ba25b'
down_revision = '760200d81252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_sessions')
    op.drop_table('cart_items')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('payment_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('provider', sa.VARCHAR(length=100), nullable=True),
    sa.Column('account_no', sa.INTEGER(), nullable=True),
    sa.Column('expiry', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_payments')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sku', sa.INTEGER(), nullable=True),
    sa.Column('copy', sa.VARCHAR(length=500), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('inventory', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_products_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_products')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('_password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('user_payment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_payment_id'], ['payments.id'], name='fk_users_user_payment_id_payments'),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_cart_items_product_id_products'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_cart_items_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_cart_items')
    )
    op.create_table('shopping_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('cart_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart_items.id'], name='fk_shopping_sessions_cart_id_cart_items'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_shopping_sessions_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_shopping_sessions')
    )
    # ### end Alembic commands ###
