"""changing long description from copy

Revision ID: 8966469c1def
Revises: 1f55c3216243
Create Date: 2023-08-30 15:48:33.802798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8966469c1def'
down_revision = '1f55c3216243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_desc', sa.String(length=500), nullable=True))
        batch_op.drop_column('copy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copy', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('long_desc')

    # ### end Alembic commands ###
